### ISSUE TITLE
Bug: range component output includes spousal filing date when not applicable

### ISSUE THREAD

**Issue by MikePiper** [MikePiper/open-social-security#11]
relates to branch: component-for-range-of-options

Relevant inputs:
personA born April 1951, PIA 2300
personB born April 1960, PIA 1000

Possible output when clicking on range chart:
NOTE: Spousal benefit may be claimed before retirement benefit.
Selected Option: Expected PV = $1,028,841, 99.6% of max. PV
    Claim dates: You (retirement) 2/2021, Spouse (retirement) 11/2022, You (spousal) 11/2022,

In reality, there's no option for spousal benefits for personA. While personA has the old deemed filing rules, he/she is more than 8 years older than (nondisabled) personB, with a PIA of at least 50% of personB's PIA. So there's no way for personA to ever get spousal.

Also, "You (spousal)" shouldn't be in the output. (Lines 66 and 80 of claimDates.ts appear to be the issue here. But I haven't yet fully thought through the purpose of those lines, so I don't yet have a suggestion.)

And "Spouse (spousal)" should be in the output, but it isn't.

**Comment by brian-courts** [comment]
Please see my comment on issue #11 regarding improved claim date outputs.

**Comment by brian-courts** [comment]
Oops, I meant issue #14.

**Comment by MikePiper** [comment]
Today's commit (link below) eliminates this bug since there's completely different code now being used to generate these strings.
https://github.com/MikePiper/open-social-security/commit/5f6b5228b92c7dc4e446391849d34f06163a5972
