### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by MikePiper** [MikePiper/open-social-security#17]
I think we can do some code cleanup at this point. I'm happy to take it on (and I'll check carefully to see if anything causes problems, as I could be wrong about any of the below items). But I just wanted to check with you in advance in case there's something you have planned which would make this obviously inadvisable.

I think we can eliminate the `cutString` and `cutOrNoCutString` variables and related code. (Now tapping into the scenario object per my last commit.)

Ditto for `selectedClaimDatesString` and `selectedPercentString`.

Also `ClaimDates.benefitDatesString()`.

Similarly, I'm looking into `pvFractionArrays` in range.ts, as well as related code. (Maybe not, as this is needed for the graph, not just the string output?)

**Comment by brian-courts** [comment]
If you determine those variables are no longer needed, feel free to eliminate them, and do general cleanup also.

`pvFractionArrays` are currently used to determine color numbers for the graph, in addition to string output. If you have a different way of generating the strings, the `pvFractionArrays` would no longer be needed.

In fact, the color determination could be streamlined quite a bit if we don't need the fractions for the string. I can do that streamlining after you've done other cleanup.

**Comment by MikePiper** [comment]
I just made a push that removes the variables/functions discussed above, except for `pvFractionArrays`.

`pvFractionArrays` is still being used for the strings in the hover tooltip.

Separately, what would be your thoughts on removing the tooltip?

It's already super easy/fast to just click around on the graph/chart to see the results of any desired location. And that way there would be no need to essentially have duplicate versions of certain functionality. (A related point is a concern about how the tooltip cannot as fully explain the meaning of the filing dates in question.)

**Comment by brian-courts** [comment]
I eliminated the pvFractionArrays as part of streamlining the color determination process.

I think the hover tooltip is useful for those who want an easy way to compare the option under the pointer with the selected choice. The user has the information for both items on the screen at the same time. He/she doesn't have to remember, for example, "Now what were those three claim dates that just disappeared from my screen?"

**Comment by MikePiper** [comment]
Closing this issue as resolved. Thanks for the help with it!
