### ISSUE TITLE
Spouse Survivor Benefit Computation?

### ISSUE THREAD

**Issue by davidabarrett** [MikePiper/open-social-security#2]
https://www.aarp.org/retirement/social-security/questions-answers/eligible-retirement-and-survivor-benefits/

How is the line "If your spouse outlives you" calculated?   

In general, do you have links to the literature you used to construct the code?

**Comment by brian-courts** [comment]
@MikePiper Mr. Barrett (and other interested parties) may not be concerned about the details of how the survivor benefit is calculated. They may want to understand the conditions under which the numbers provided are accurate.  For example (and I'm guessing a little here about the conditions):

The benefits in the "If your spouse outlives you" line under either the "Recommended Strategy" or "Alternative Claiming Strategy" are those which your spouse would receive if:
a) Your spouse survives you after the last claim specified in the relevant strategy. 
b) You claimed your benefit(s) and your spouse claimed his/her benefit(s) on the date(s) specified. 
c) Your spouse has reached his/her Full Retirement Age.
... and any other conditions which apply to the calculation.

The benefits in the "If you outlive your spouse" line under either the "Recommended Strategy" or "Alternative Claiming Strategy" are those which you would receive if:
a) You survive your spouse after the last claim specified in the relevant strategy. 
b) You claimed your benefit(s) and your spouse claimed his/her benefit(s) on the date(s) specified. 
c) You have reached your Full Retirement Age.
... and any other conditions which apply.

The benefits shown might apply even if some of the above condition's are not met, but not always. I've seen in my case that my wife would receive more if she claimed survivor benefits before her specified claiming date (at age 70) if I should die before then, but that option is not shown in the output.

I understand that it is impractical to include every possible circumstance in a simple, readable output table like the one you provide. Some explanation of the assumptions might be included in the "About" page for the detail-oriented users.

**Comment by brian-courts** [comment]
@MikePiper 
Thanks for your quick response. 

Your statement of the assumptions is clear and concise. That's probably one of the reasons people buy your books..
