### ISSUE TITLE
URL query parameters missing child inputs

### ISSUE THREAD

**Issue by batsatt** [MikePiper/open-social-security#39]
When child data is entered, it is not reflected in the URL so saving the link and re-using it doesn't work correctly.

The last query parameter defined in `home.component.html` is `&&children={{qualifyingChildrenBoolean}}`; looks to me like this needs to be updated to include parameters for the `scenario.children` array.

**Comment by MikePiper** [comment]
@batsatt Thank you! I've tried probably 7-8 times to figure out a way to make this work. Never any success, and it just seemed ultimately beyond my Angular skills. Your snippet was enough to get me rolling on a solution that works, as far as I can tell.

Just rolled it out. (You might have to "shift+refresh".) Of course if you see any situations where it isn't working correctly, please let me know.
