### ISSUE TITLE
Children-only benefits are not included in present value calculation for a couple

### ISSUE THREAD

**Issue by brian-courts** [MikePiper/open-social-security#4]
As currently written, the calculator does not include benefits that would be received by children after both parents are deceased.

In the "calculateCouplePV" routine in presentvalue.service.ts, starting at line 317, the probability-factored sum of benefits for a given year is calculated as follows:
 
`            //Apply probability alive to annual benefit amounts
              let annualPV:number =
                probabilityAalive * probabilityBalive * calcYear.annualBenefitBothAlive +
                probabilityAalive * (1 - probabilityBalive) * calcYear.annualBenefitOnlyPersonAalive +
                probabilityBalive * (1 - probabilityAalive) * calcYear.annualBenefitOnlyPersonBalive`

            `//Discount that probability-weighted annual benefit amount to age 62`

The following line could be added to include benefits to children after both parents are deceased:

`         + (1 - probabilityAalive) * (1 - probabilityBalive) * calcYear.annualBenefitBothDeceased`

However, doing so would overestimate the benefits received by families with adult disabled children, because children are assumed to live forever.

**Comment by MikePiper** [comment]
Thanks again for bringing this to my attention. I've implemented the change suggested.

I'm closing this issue, but for the record I agree that the current model (in which mortality for children is simply ignored) is not ideal (in particular for adult disabled children) and merits further consideration/discussion. I'll be leaving the other related issue open for this reason.
