### ISSUE TITLE
Save your inputs link drops discount rate if 0%

### ISSUE THREAD

**Issue by Gregable** [MikePiper/open-social-security#63]
Very tiny corner case. This link with URL parameters:

![image](https://github.com/MikePiper/open-social-security/assets/25519/cdf52b1b-751a-4c83-8195-5c3b5f977cef)

Does not save the "Real discount rate" if it had been set to the value `0`.

**Comment by MikePiper** [comment]
Thank you for finding this @Gregable. Fixed and marking as closed.
