### ISSUE TITLE
Survivor Benefits appear incorrectly calculated

### ISSUE THREAD

**Issue by Gregable** [MikePiper/open-social-security#64]
To reproduce, I entered the following scenario into Open Social Security:

```
Marital Status: Widow(er)
Gender: Male
Date of Birth: 4 / 15 / 1960
PIA: 1000
Already filed for retirement benefits: no
Already filed for survivor benefits: no
```

```
Gender: Female
Date of Birth: 4 / 15 / 1960
Month/Year of death: 4 / 2020
PIA: 3000
Already filed for retirement benefits: no
```

The recommended strategy printed is:

```
You file for your survivor benefit to begin 2/2024, at age 63 and 10 months.
You file for your retirement benefit to begin 4/2030, at age 70 and 0 months.

2024	$0	$29,003	$29,003
2025	$0	$31,640	$31,640
2026	$0	$31,640	$31,640
2027	$0	$31,640	$31,640
2028	$0	$31,640	$31,640
2029	$0	$31,640	$31,640
2030	$11,160	$20,480	$31,640
2031+	$14,880	$16,760	$31,640
```

My understanding of survivor's benefit, possibly incorrect, is that for someone who:

1. Dies before FRA (age 67 in the case of both of these people)
2. And hadn't yet filed

Then the base survivor benefit will be the deceased's PIA ($3,000), and this will be adjusted proportionally between 71.5% and 100% of the survivor's age when they file for survivor's benefit, in proportion to how many months between age 62 and FRA (67).

In the suggested filing of age 63 and 10 months, the survivor is filing at 22 months after age 62 out of `12 * 5 = 60` months. `22 / 60 = 0.3666`. 

`$3,000 * (71.5% + (29.5% * 0.3666)) = $2,145`

Annually, that's $25,740, but your calculation shows a $31,640 benefit starting in 2025.

A $31,640 benefit would suggest opensocialsecurity is calculating a 12.1% reduction in benefits rather than the 18.7% reduction calculated above.

------

The math gets a little messy for the adjustment based on the survivor's filing date and I'm not sure I understand what I'm doing there correctly, so I tried something different. Using the same inputs as above, I then selected a alternative claiming strategy:

The survivor files for both retirement and survivor benefits on 4 / 2027. 

This should be FRA for the survivor, and thus iiuc the survivor benefit should be exactly $3,000 / month, the deceased's PIA. Doing so, shows me an error:

> Survivor benefits do not continue to grow as a result of waiting beyond your survivor FRA. Please choose a date that is no later than your survivor FRA (or no later than your earliest possible retroactive filing date, if you have already reached your survivor FRA).

This is confusing, as 4/2027 should be the survivor FRA.

I tried changing the values and the latest point where I don't get an error is 12/2026. I'm not sure why that might be the case.  Is FRA being calculated as someone born in 1958 maybe, with a FRA at 66y 8mo?

Regardless, when I do so, I get the following text:

```
The present value of the strategy you selected is $405,562, as compared to a present value of $440,056 from the recommended strategy, a difference of -$34,494 (-7.8%).

2026	$978	$2,022	$3,000
2027	$11,733	$24,267	$36,000
2028	$11,733	$24,267	$36,000
2029	$11,733	$24,267	$36,000
2030	$11,733	$24,267	$36,000
2031+	$11,733	$24,267	$36,000
```

This doesn't seem correct because the survivor is filing at earlier than FRA, but it would be the correct survivor benefit if the FRA was indeed 12/2026. However, the personal benefit is indeed showing a reduction that looks correct for a 67y FRA.

Anyway, not sure exactly what's failing, but I thought I might share the debug case in case it's useful for testing. If I can provide more information, let me know.

**Comment by Gregable** [comment]
Edit: I was reading the difference in strategies text backwards, so I removed that part from the filed issue.

**Comment by MikePiper** [comment]
@Gregable 

There are two points of note here.
1) His survivor FRA (as distinct from retirement/spousal FRA) in this case is 66 and 8 months, rather than 67. See here:
https://www.ssa.gov/benefits/survivors/survivorchartred.html

2) The denominator in the reduction multiplier is the number of months between 60 (rather than 62) and survivor FRA. So we're multiplying the maximum 28.5% reduction by 34 months early ÷ 80 total months between 60 and his survivor FRA. 0.285 x 34 / 80 = 0.121, hence the 12.1% reduction.

Does that fully resolve the issue, or do you feel that there's something else that you have raised that I did not address?

**Comment by Gregable** [comment]
Aha, I hadn't realized that survivor FRA had different age brackets. Interesting, I wonder how that evolved. Regardless, I think you are correct. As well, thank you for the time explaining where I misunderstood!
