### ISSUE TITLE
Spousal Benefits are Calculated Incorrectly

### ISSUE THREAD

**Issue by bdr60** [MikePiper/open-social-security#65]
A spouse cannot receive a 50% spousal benefit unless they start taking their own benefit at full retirement age.  The calculator is quite misleading in this respect and indicates that the spouse's benefit jumps to 50% even if they start taking SS before their FRA.

**Comment by MikePiper** [comment]
@bdr60 if you would like me to investigate this issue, please copy the link that appears in the paragraph below the "submit" button on the calculator, in order to provide me with inputs that you provided to the calculator.

**Comment by bdr60** [comment]
https://opensocialsecurity.com/?additionalInput=false&disabilityShow=false&workingShow=false&pensionShow=false&mortalityShow=false&childrenShow=false&discountShow=false&cutShow=false&marital=married&discount=1.93&cutAssumption=false&cutYear=2034&cutPercent=23&aGender=male&aDOBm=10&aDOBd=5&aDOBy=1960&aDisability=false&aPIA=3100&aFixedRBm=&aFixedRBy=&aWorking=false&aQuitm=&aQuity=&aEarnings=0&aFiled=false&aFiledSurvivor=false&aFixedSurvBm=&aFixedSurvBy=&aFiledMotherFather=false&aFixedMFBm=&aFixedMFBy=&aEligiblePension=false&aPensionm=1&aPensiony=2020&aGovPension=0&aPIA2=1000&aMortality=SSA2020&aDeathAge=100&bGender=female&bDOBm=9&bDOBd=15&bDOBy=1958&bDODm=4&bDODy=2020&bDisability=false&bPIA=600&bFixedRBm=&bFixedRBy=&bWorking=false&bQuitm=&bQuity=&bEarnings=0&bFiled=false&bEligiblePension=false&bPensionm=1&bPensiony=2020&bGovPension=0&bPIA2=1000&bMortality=SSA2020&bDeathAge=100&children=false&numberOfChildren=0

MIke,
The 50% benefit is way off because it does not seem to be taking
appropriate reductions for either me or my spouse's early retirement date.
Wish it really worked that way.  The maximum spousal benefit is 50% of my
benefit at FRA.  This benefit is reduced if I take SS early and/or my wife
takes it early.  In the linked example the spousal benefit could not be any
more than half of $33,893, which is $16,947, but the total benefit is
$18,040.  Even the $16,947 would be too much because the spouse is taking
their benefit before FRA.

**Comment by MikePiper** [comment]
Just did a quick manual check. Everything looks good to me. Please note that in the scenario provided, the spousal benefit itself is not reduced for early filing, as it does not begin until after full retirement age. Each person's retirement benefit is reduced for early filing, but not the spousal benefit.
https://docs.google.com/spreadsheets/d/1CKp6zDz-4Z1ONND0YsimLnG67D5jdmx1CBo4WeCpX1c/edit?usp=sharing

**Comment by bdr60** [comment]
Mike, the spousal benefit can never be more than 50% of the primary
beneficiary and the spousal benefit is reduced for filing early, even if
the spousal benefit is not "turned on"  until later.
See this article:
https://www.cnbc.com/2021/03/29/claiming-social-security-early-can-affect-spousal-benefits-heres-how.html
I have verified this with a SS expert.
Thanks, Brian

**Comment by MikePiper** [comment]
@bdr60 In the example provided, the spousal benefit is $950/month, which is less than 50% of the other person's primary insurance amount ($3,100).

Respectfully, a CNBC article is not an authoritative source.

If you are interested, you can find the relevant POMS reference below. We are concerned with "method C" in this case, as in POMS jargon "A" refers to a retirement benefit and "B" refers to a spousal benefit.
https://secure.ssa.gov/poms.nsf/lnx/0300615020

Or CFR 404.411(d) here:
https://www.ssa.gov/OP_Home/cfr20/404/404-0411.htm

**Comment by bdr60** [comment]
Mike, I had the misconception that the 50% spousal benefit was based on
whatever was in the "Your Annual Retirement Benefit" column .  But I see
that it is based on what you would get at FRA.  The spouse has complete
control of any potential reduction.
So, I learned something from the calculator.  Thanks!
