### ISSUE TITLE
Ability to explore survivor benefits

### ISSUE THREAD

**Issue by dcabler** [MikePiper/open-social-security#66]
There doesn't appear to be an option to see what survivor/widow benefits would look like for different assumptions regarding the date of death of one spouse.  For example, suppose both spouses have an FRA of 67.  Suppose one plans to start SS at age 66 and the other at age 70.   Spouse #1 is older than Spouse #1.  
With the plan in place now, what does Spouse 1 benefits look like if spouse 2 dies at different ages?
There is an assumed age of death feature, but that feature reoptimizes.  This request is assuming the optimization has already happened and decisions have been made.  Now the user would like to see the effect of those decisions for different actual date of deaths.  Assuming death occurs at the end of the year specified is fine.

Best regards

**Comment by dcabler** [comment]
> There doesn't appear to be an option to see what survivor/widow benefits would look like for different assumptions regarding the date of death of one spouse. For example, suppose both spouses have an FRA of 67. Suppose one plans to start SS at age 66 and the other at age 70. Spouse #1 is older than Spouse #1. With the plan in place now, what does Spouse 1 benefits look like if spouse 2 dies at different ages? There is an assumed age of death feature, but that feature reoptimizes. This request is assuming the optimization has already happened and decisions have been made. Now the user would like to see the effect of those decisions for different actual date of deaths. Assuming death occurs at the end of the year specified is fine.
> 
> Best regards

There is a typo.  Assume spouse #1 is older than Spouse #2.

Best.

**Comment by MikePiper** [comment]
I am not following. Could you provide a more full example, with the other relevant inputs, and what you would like to see the calculator calculate?

Is this not addressed via the color-coded chart (or accompanying dropdown inputs)?

Also just as additional information, the intention of the calculator is indeed to be a decision optimizer, not a benefit calculator per se.

**Comment by dcabler** [comment]
Understood it’s a decision optimizer.  Once the decision is made, I would like to see what happens when reality gets in the way of the plan.

As I understand the description of the color coding chart, no, this isn’t what I’m looking for.   I don’t see in the description where it would calculate widow(er) benefits for a surviving spouse.

Regardless, here is the concrete example.
Spouse 1: (M)
DOB 6/9/1961
PIA at FRA is $3,763

Spouse 2: (F)
DOB 4/9/1960
PIA at FRA is $2,307

Ran the tool using the 2017 CSO Nonsmoker Super-Preferred mortality table
Spouse 1: Starts at age 70 years, 0 months
Spouse 2: Starts at age 65 years, 11 months

So that’s the plan.
Assume that Spouse 1 dies first.
What I’d like to see is what Spouse2’s benefits and survivor benefits are if Spouse 1 dies at age 63, 64, 65…  etc.   It’s fine if the tool assumes that the death happens at the end of the year, if that helps the computations.

That’s it.  Yes if things don’t go according to plan “it will be what it will be” but I still want to understand the impact.

If it’s not possible for the tool to explore this, then I completely understand.  I do, however, see this as something that’s missing in social security analysis.  Mike Piper’s book, “Social Securiity Made Simple” probably has the most comprehensive description of widow(er) benefits in chapter 4 and appendix A.  Taking the description from your book and making a tool out of it would be worthwhile, I think.  I haven’t seen anything like that anywhere.  The closest thing I’ve seen is where #cruncher created a spreadsheet on Bogleheads using the book’s description.  It’s located in this post: Social Security and survival benefits - Bogleheads.org<https://www.bogleheads.org/forum/viewtopic.php?p=7458447#p7458447>

So if opensocialsecurity.com can’t do this today perhaps it can be considered 1 of 2 ways:

  1.  An enhancement request
  2.  A request for a new tool

Best regards!

**Comment by MikePiper** [comment]
Ah, I see what you mean. Yes, this is definitely not an intended use case for the calculator.

You could get the results by using the widow(er) filing status and fudging the DoB for the person who we're assuming dies, but this is definitely an "off label" use.

**Comment by MikePiper** [comment]
Just adding that this request feels much more in line with the spirit of the SSA.tools benefit calculator.

**Comment by dcabler** [comment]
I used that one quite a bit to see what my benefits would be each year, but the SSA site itself has evolved over the years to the point where you can now (finally) tell it whether or not (and how much) you expect to earn going forward.  Then you can directly get your estimated benefits without all of the cutting and pasting of your earnings record into the tool.

That said, a quick glance shows that they’ve added some features to the tool that weren’t there previously.   Nothing obvious, though, about calculating survivor benefits.  Will check it out.

In the meantime, I did get #cruncher’s spreadsheet working in the post he made on Bogleheads.  It does work, but it does lack some granularity, but it’s good enough for what I’m looking for.

The main usefulness for this as I see it, isn’t just to show you what might happen in a certain year if one or the other couple passes.  For some people, depending on a number of factors, it might be wise to change the plan to further maximize the survivor’s overall benefits not just annually but also over time…

Cheers!
