### ISSUE TITLE
bad assumption for someone born before 1954?

### ISSUE THREAD

**Issue by djchawk** [MikePiper/open-social-security#75]
This issue is not necessarily a defect, as I suspect the calculator is working as designed, but I think the design is based on an incorrect assumption.

I'm the working spouse, 7 years younger than my non-working spouse (who has insufficient lifetime credits to collect her own benefit).  Spouse default birth year when you load the page is 1960, and the answer to the question "Has your spouse already filed for retirement benefits?" defaults to "No".  If I change spouse birth year to any year prior to 1954, the UI changes to a default answer of "Yes (spouse already filed)" and a date field appears. The radio button cannot be changed from "Yes" to "No", because I **think** you've made the assumption that anybody born before 1954 has surely already filed.  However, my spouse, though 70 years of age, has NOT filed, because I've been employed, and I have not filed (age 63).

I may be wrong that you've made this assumption, but I definitely cannot change that radio button from "Yes spouse has already filed" to "No spouse has not filed".  Thank you for the calculator.

**Comment by MikePiper** [comment]
Yes, it assumes a person beyond age 70 has already filed for their retirement benefit. In the case of a person with a PIA of zero, it makes no difference at all, as it won't affect that person's spousal or survivor benefit amounts.
