### ISSUE TITLE
Miscalculates at 5/29 (60 yds 7 mo) 

### ISSUE THREAD

**Issue by Bjahnsen** [MikePiper/open-social-security#77]
When I get the “best option” takes survivor benefit at 5/2030 which is 60 yrs and 7 months, it is wrong in the survivor benefit. 
if I change to one month later 6/2030, it reduces the survivor benefit by $500. 
therefor the calculator is not useful for me. It’s great - but scared to use it really. 

https://opensocialsecurity.com/?additionalInput=true&&disabilityShow=false&&workingShow=true&&pensionShow=false&&mortalityShow=true&&childrenShow=false&&discountShow=false&&cutShow=false&&marital=survivor&&discount=2.17&&cutAssumption=false&&cutYear=2034&&cutPercent=23&&aGender=female&&aDOBm=10&&aDOBd=12&&aDOBy=1968&&aDisability=false&&aPIA=1274&&aFixedRBm=&&aFixedRBy=&&aWorking=true&&aQuitm=10&&aQuity=2035&&aEarnings=4200&&aFiled=false&&aFiledSurvivor=false&&aFixedSurvBm=&&aFixedSurvBy=&&aFiledMotherFather=false&&aFixedMFBm=&&aFixedMFBy=&&aEligiblePension=false&&aPensionm=1&&aPensiony=2020&&aGovPension=0&&aPIA2=1000&&aMortality=NS1&&aDeathAge=100&&bGender=male&&bDOBm=4&&bDOBd=21&&bDOBy=1958&&bDODm=1&&bDODy=2007&&bDisability=false&&bPIA=2707&&bFixedRBm=&&bFixedRBy=&&bWorking=false&&bQuitm=&&bQuity=&&bEarnings=0&&bFiled=false&&bEligiblePension=false&&bPensionm=1&&bPensiony=2020&&bGovPension=0&&bPIA2=1000&&bMortality=SSA2020&&bDeathAge=100&&children=false&&numberOfChildren=0

**Comment by Bjahnsen** [comment]
Sorry it is 5/2029 not 5/2030

**Comment by MikePiper** [comment]
I do not see any error in the calculation. In the second case (survivor benefit filing 6/2029 instead of 5/2029) the monthly survivor benefit is greater as one would expect. Also, please note that withholding from the earnings test is applicable here.

**Comment by Bjahnsen** [comment]
Please see attached photo. Top to bottom. 5/29 is $29,288 at Full Survivor1/30 is $28,737 at Full survivor (full year after FRA in 2036) Almost $500 less. Only thing I changed was the date to later. Am I missing something? Thank for your help. Beth JahnsenOn May 21, 2024, at 4:26 PM, MikePiper ***@***.***> wrote:﻿
I do not see any error in the calculation. In the second case (survivor benefit filing 6/2029 instead of 5/2029) the monthly survivor benefit is greater as one would expect. Also, please note that withholding from the earnings test is applicable here.

**Comment by MikePiper** [comment]
I got a chance today to do a manual calculation. Everything looks correct to me.
https://docs.google.com/spreadsheets/d/1PHqHKPe3A-q7OCpVpnTZw_cknywVVS4CrJ6JDCDUfbs/edit#gid=0

Note that the key point here is that more months of withholding were necessary in the 5/2029 filing date case, which results in a LATER adjusted benefit date after the adjustment occurs at FRA.
