### ISSUE TITLE
Alternate scenario does not calculate the spouses inputted start date

### ISSUE THREAD

**Issue by Varktamer37** [MikePiper/open-social-security#78]
I've been running various alternate social security scenarios at the bottom of the page.  At the moment, the calculator continues to solve for the spouse using its preferred start date (age 67) from the original calculation and not the inputted start date of 62.

**Comment by MikePiper** [comment]
@Varktamer37 if you would like me to investigate, I need you to provide the link from the bottom of the page that saves all the inputs used.

**Comment by Varktamer37** [comment]
Mike,
I'm sorry...

[right-click this link](https://opensocialsecurity.com/?additionalInput=true&&disabilityShow=false&&workingShow=true&&pensionShow=false&&mortalityShow=true&&childrenShow=false&&discountShow=false&&cutShow=false&&marital=married&&discount=2.19&&cutAssumption=false&&cutYear=2034&&cutPercent=23&&aGender=male&&aDOBm=8&&aDOBd=13&&aDOBy=1959&&aDisability=false&&aPIA=3748&&aFixedRBm=&&aFixedRBy=&&aWorking=false&&aQuitm=&&aQuity=&&aEarnings=0&&aFiled=false&&aFiledSurvivor=false&&aFixedSurvBm=&&aFixedSurvBy=&&aFiledMotherFather=false&&aFixedMFBm=&&aFixedMFBy=&&aEligiblePension=false&&aPensionm=1&&aPensiony=2020&&aGovPension=0&&aPIA2=1000&&aMortality=fixed&&aDeathAge=75&&bGender=female&&bDOBm=12&&bDOBd=7&&bDOBy=1966&&bDODm=4&&bDODy=2020&&bDisability=false&&bPIA=1154&&bFixedRBm=&&bFixedRBy=&&bWorking=true&&bQuitm=12&&bQuity=2036&&bEarnings=25000&&bFiled=false&&bEligiblePension=false&&bPensionm=1&&bPensiony=2020&&bGovPension=0&&bPIA2=1000&&bMortality=fixed&&bDeathAge=100&&children=false&&numberOfChildren=0)

I asked for the recommendation which came back 70 for me(with die early at 75) and 67 for the better half(live to 100).  And then I tried an alternative of me at my normal age of 66y 10m and her early at 62.  But this calculation kept her at 67 (2033), which made me wonder if I had good results to start with.

Thank you for checking (and for this calculator!!).  It's the weekend and I didn't think you'd get to it until sometime next week.

**Comment by MikePiper** [comment]
@Varktamer37 
It's the earnings test. You have input that she is earning $25k/month, which puts her annual earnings way beyond what's necessary for full withholding of her benefit -- until she reaches FRA and the earnings test no longer applies. So even if you're selecting an earlier filing date for her, in the table with year-by-year amounts, nothing actually shows up for her until the year she reaches FRA.

https://www.ssa.gov/oact/cola/rtea.html

**Comment by Varktamer37** [comment]
"Oh my gosh....read the question Rob."  Again, I am so sorry Mike.  Thank you for setting me straight.

**Comment by MikePiper** [comment]
@Varktamer37 No problem!
