### ISSUE TITLE
Incorrect Spousal benefit calculation?

### ISSUE THREAD

**Issue by Lunchbox333** [MikePiper/open-social-security#80]
(Following your article, I'll use Jane and Bob for examples, with Jane as the higher earner)  

As I understand it, the Spousal Benefit is derived from the spouses PIA, and is NOT affected by the actual date that the spouse files for SS.

That is verified by your calculator so long as Jane files BEFORE Bob.  But.  I believe there is a bug in your code if Bob files for himself first.

The problem scenario is:  Bob files first. Then at a later date, Jane files AND Bob files for spousal benefits at the same time.  In that scenario, as I modify Jane's retirement date, leaving Bob's date constant, Bob's spousal benefit is changing! That is incorrect, right?  Only Jane's PIA matters, not the age that she files.  

I have been looking into this for hours, and the only explanation I can find is that the calculator is in error.  If I am missing something, I apologize.

Regards,
Bill

**Comment by MikePiper** [comment]
@Lunchbox333 I've written many articles about Social Security over the years, so I'm not sure which one you're referring to.

If you'd like me to investigate a potential error/bug, I'll need you to please post the link/URL from the bottom of the page, which provides the inputs in question.

**Comment by Lunchbox333** [comment]
I continued to research this, and have finally found the explanation for the results that your calculator is returning. The spousal calculation can get quite confusing depending on age and work history.  Anyway. No bug!  My apologies.

**Comment by MikePiper** [comment]
@Lunchbox333 Happy to hear it! No apology needed. And yes, benefit calculations can get complicated sometimes.
