### ISSUE TITLE
Error on older wife date calculation

### ISSUE THREAD

**Issue by reformedman** [MikePiper/open-social-security#82]
Wife was born 1964, husband was born 1969.
When entering info in the opensocialsecurity calculator, on top of page it works fine and gives suggested plan fine.
When entering info in the bottom of the page for ALTERNATE CLAIMING STRATEGY, I enter the following date:
```
Your month/year to claim retirement benefit: 5/2031
Your spouse's month/year to claim retirement benefit: 10/2026
Your spouse's month/year to claim spousal benefit: 6/2031
```

The error I get in pink background and red letters is the following:
`Per new deemed filing rules, a person's spousal benefit date must be the later of their own retirement benefit date, or their spouse's retirement benefit date.`

Both of these things are true so I don't understand why I'm getting this error.

**Comment by MikePiper** [comment]
@reformedman It must be the later _of_ the two dates, not later _than_ both of the dates. In this case, due to deemed filing the spousal filing date would have to be 5/2031.
