### ISSUE TITLE
Spouses early benefit is not calculated correct

### ISSUE THREAD

**Issue by MJShaw9999** [MikePiper/open-social-security#83]
Spouses early benefit is not calculated correct. At least it does not match the Social Security page. Here are the numbers from the spouse (lower earner).  Starting benefits for the spouse was suggested now (62 years and 11 months) but on the table of benefits a yearly benefit of $10,776 (which would be 898 per month. However the actual amount at 62 and 11 month from the social security page is 847. I have summarized this below and also added when the benefit would be 898.

```
YY.MM     Monthly / Yearly amounts   Comments
62.11        847      /    10,164             Actual amount now
63.7          898      /    10,776             Age when the benefit would be 898 / 10,776
67             1204     /     14,448             At full retirement age (67)
```

Mike

**Comment by MikePiper** [comment]
@MJShaw9999 If you would like me to look into this, I will need you to provide the link that appears in the paragraph below the "submit" button on the calculator, in order to provide me with inputs that you provided to the calculator.

**Comment by MJShaw9999** [comment]
https://opensocialsecurity.com/?additionalInput=false&&disabilityShow=false&&workingShow=false&&pensionShow=false&&mortalityShow=false&&childrenShow=false&&discountShow=false&&cutShow=false&&marital=married&&discount=2.1&&cutAssumption=false&&cutYear=2034&&cutPercent=23&&aGender=male&&aDOBm=7&&aDOBd=7&&aDOBy=1960&&aDisability=false&&aPIA=3327&&aFixedRBm=&&aFixedRBy=&&aWorking=false&&aQuitm=&&aQuity=&&aEarnings=0&&aFiled=false&&aFiledSurvivor=false&&aFixedSurvBm=&&aFixedSurvBy=&&aFiledMotherFather=false&&aFixedMFBm=&&aFixedMFBy=&&aEligiblePension=false&&aPensionm=1&&aPensiony=2020&&aGovPension=0&&aPIA2=1000&&aMortality=SSA2020&&aDeathAge=100&&bGender=female&&bDOBm=8&&bDOBd=23&&bDOBy=1961&&bDODm=4&&bDODy=2020&&bDisability=false&&bPIA=1204&&bFixedRBm=&&bFixedRBy=&&bWorking=false&&bQuitm=&&bQuity=&&bEarnings=0&&bFiled=false&&bEligiblePension=false&&bPensionm=1&&bPensiony=2020&&bGovPension=0&&bPIA2=1000&&bMortality=SSA2020&&bDeathAge=100&&children=false&&numberOfChildren=0

**Comment by MikePiper** [comment]
The calculation shown is correct. This is just a basic case of dual entitlement. You can find the dual entitlement rules here:
https://secure.ssa.gov/apps10/poms.NSF/lnx/0300615020

In this case it's a "method C" situation. So we have a spousal benefit equal to 50% of personA's PIA, minus personB's own PIA.

3327/2 - 1204 = $459.50

**Comment by MJShaw9999** [comment]
From the information you pasted below it indicates the higher benefit is due to spousal benefit but that will not start for several years until I start. So far this does not make sense.

 

Michale Shaw

**Comment by MikePiper** [comment]
That's correct -- SpouseB's benefit as SpouseA's spouse cannot begin until SpouseA's retirement benefit has begun.
