### ISSUE TITLE
Calculated current year annual retirement benefit does not match actual benefit being paid

### ISSUE THREAD

**Issue by sengsational** [MikePiper/open-social-security#84]
This might be more of a feature request than an issue, but I'll relate what I encountered.

Scenario: Higher earner has not started benefits, lower earner (spouse) has started benefits some years ago.  PIA for high earner available on SS statement (expected/good).  PIA for lower earner not available on SS statement, or anywhere, as far as I know; the value seems irrelevant.  But it's a required input (unexpected/bad).

First, what I did was find an old PIA for the lower earner (from 2017), and inflate that by the 7 COLA percentages, getting me to a 2024 PIA (not sure this is legit), and use that number in PIA for the lower earner.  Entered the month/year benefits started.  The result (unexpected) was that the spouse's annual retirement benefit did not equal what she was actually getting from SS for 2024.

What I ended-up doing was iterate on the PIA amount for spouse until the 2024 spouse's annual retirement benefit on the output was roughly the value she was actually getting in benefits.

Would it be possible and appropriate to allow the input field for someone who has already started benefits to be the total "benefit before deductions", as indicated on the annual "Notice of Cost-0f-Living Adjustment (COLA)" letter?  This would be instead of the other existing input fields.

**Comment by MikePiper** [comment]
The PIA of the lower earner is still a relevant input.

To find the PIA of somebody who already filed, we can just use arithmetic and their current monthly benefit and filing age (e.g., if they filed 36 months prior to FRA, their monthly retirement benefit is 80% of their PIA).

Alternatively a calculator such as the one at SSA.tools can quickly calculate a person's PIA.
